jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
        Ensiie\Bundle\UserBundle\Entity\User :
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
            
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_PROF,ROLE_ETU,ROLE_GESTION]
        ROLE_SUPER_ADMIN: [ROLE_SUPERADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        main:
            entity: { class: Ensiie\Bundle\UserBundle\Entity\User, property: username }
                    
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider : main 
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /myspace
            logout:
                path: /logout
                target: /
            
            
    access_control:
        - { path: ^/admin, roles: ROLE_GESTION }
        - { path: ^/etu, roles: ROLE_ETU }
        - { path: ^/prof, roles: ROLE_PROF }
        - { path: ^/password/change, roles: [ROLE_GESTION, ROLE_ETU, ROLE_PROF] }