ensiie_homepage:
    pattern: /{tri}
    defaults: { _controller:EnsiieMainBundle:Home:index, tri:exam }
    requirements:
        tri: exam|promo
    
ensiie_prof:
    pattern: /prof
    defaults: { _controller:EnsiieMainBundle:Prof:index }
    
ensiie_etu:
    pattern: /etu
    defaults: { _controller:EnsiieMainBundle:Etu:index }
    
ensiie_admin:
    pattern: /admin
    defaults: { _controller:EnsiieMainBundle:Admin:index }

ensiie_afterlogin:
    pattern: /myspace
    defaults: { _controller:EnsiieMainBundle:AfterLogin:redirect }