ensiie_examen_affect:
    pattern: /prof/examen_affect
    defaults: { _controller:EnsiieDataBundle:Examen:affect }
    
ensiie_examen_upload:
    pattern: /prof/examen_upload
    defaults: { _controller:EnsiieDataBundle:Examen:upload }