ensiie_examen_affect:
    pattern: /prof/examen_affect
    defaults: { _controller:EnsiieDataBundle:Examen:affect }

ensiie_examen_show:
    pattern: /prof/examen_show
    defaults: { _controller:EnsiieDataBundle:Examen:show }
    
ensiie_examen_remove:
    pattern: /prof/examen_remove/{id}
    defaults: { _controller:EnsiieDataBundle:Examen:remove}
    
ensiie_sujet_upload:
    pattern: /prof/sujet_upload
    defaults: { _controller:EnsiieDataBundle:FileExamen:upload }
    
ensiie_sujet_show:
    pattern: /prof/sujet_show
    defaults: { _controller:EnsiieDataBundle:FileExamen:show }
    
    
ensiie_sujet_download:
    pattern: /prof/sujet_download/{path}
    defaults: { _controller:EnsiieDataBundle:FileExamen:download }

ensiie_etudiant_examen_consult:
    pattern: /etu/examen_consult
    defaults: { _controller:EnsiieDataBundle:ExamenEtudiant:show }