ensiie_examen_affect:
    pattern: /prof/examen_affect
    defaults: { _controller:EnsiieDataBundle:Examen:affect }

ensiie_examen_show:
    pattern: /prof/examen_show/{by_owner}
    defaults: { _controller:EnsiieDataBundle:Examen:show }

ensiie_examen_depots_consulter:
    pattern: /prof/depots_consult/{id}dpt={dpt}
    defaults: { _controller:EnsiieDataBundle:Depots:show }
    
ensiie_examen_remove:
    pattern: /prof/examen_remove/{id}
    defaults: { _controller:EnsiieDataBundle:Examen:remove}

ensiie_examen_modifier:
    pattern: /prof/examen_modif
    defaults: { _controller:EnsiieDataBundle:Examen:modif }
    
ensiie_examen_modifier_id:
    pattern: /prof/examen_modifid/{id}
    defaults: { _controller:EnsiieDataBundle:Examen:modifID }
    
ensiie_examen_ajouter_etu:
    pattern: /prof/examen_ajoutEtu/{id}
    defaults: { _controller:EnsiieDataBundle:Examen:ajoutEtu }
    
ensiie_examen_retirer_etu:
    pattern: /prof/examen_retirerEtu/{id}
    defaults: { _controller:EnsiieDataBundle:Examen:retraitEtu }
    
ensiie_examen_modifier_file:
    pattern: /prof/examen_modiffile/{id}
    defaults: { _controller:EnsiieDataBundle:Examen:modifFile }
    
ensiie_sujet_upload:
    pattern: /prof/sujet_upload
    defaults: { _controller:EnsiieDataBundle:FileExamen:upload }
    
ensiie_sujet_show:
    pattern: /prof/sujet_show
    defaults: { _controller:EnsiieDataBundle:FileExamen:show }
    
ensiie_sujet_download:
    pattern: /prof/sujet_download/{path}
    defaults: { _controller:EnsiieDataBundle:FileExamen:download }

ensiie_etudiant_examen_consult:
    pattern: /etu/examen_consult
    defaults: { _controller:EnsiieDataBundle:ExamenEtudiant:show }
    
ensiie_etudiant_examen_deposer:
    pattern: /etu/examen_deposer/{id}
    defaults: { _controller:EnsiieDataBundle:ExamenEtudiant:deposer }
    

    
   