ensiie_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: EnsiieUserBundle:Default:index }
    
ensiie_inscription:
    pattern: /inscription
    defaults: { _controller: EnsiieUserBundle:Inscription:index }
    
ensiie_admin_ajoutprof:
    pattern: /admin/ajoutprof
    defaults: { _controller: EnsiieUserBundle:Prof:index }
    
ensiie_admin_retraitprof:
    pattern: /admin/retraituserb={b}
    defaults: { _controller: EnsiieUserBundle:Prof:remove }

ensiie_password_change:
    pattern: /password/change
    defaults: {_controller: EnsiieUserBundle:Password:change}