parameters:
#    ensiie_user.example.class: Ensiie\Bundle\UserBundle\Example

services:
#    ensiie_user.example:
#        class: %ensiie_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
